Changed builder flatpak for github action

diff --git a/.github/workflows/flatpak.yml b/.github/workflows/flatpak.yml
--- a/.github/workflows/flatpak.yml
+++ b/.github/workflows/flatpak.yml
@@ -78,6 +78,10 @@ jobs:
             --repo=repo \
             build \
             flatpak/com.tcs.allinonetoolkitv2.yml
+          if [ $? -ne 0 ]; then
+            echo "Flatpak build failed"
+            exit 1
+          fi
 
       - name: Create Flatpak bundle
         run: |
